package ch.eth.scu.importer.ui_elements.lsrfortessa.gui.editors.data;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;
import java.util.Map;

import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.tree.TreeModel;

import ch.eth.scu.importer.at.gui.editors.data.AbstractEditor;
import ch.eth.scu.importer.at.gui.viewers.ObserverActionParameters;
import ch.eth.scu.importer.at.gui.viewers.data.AbstractViewer;
import ch.eth.scu.importer.at.gui.viewers.data.model.AbstractNode;
import ch.eth.scu.importer.at.gui.viewers.data.model.RootNode;
import ch.eth.scu.importer.at.gui.viewers.openbis.OpenBISViewer;
import ch.eth.scu.importer.at.gui.viewers.openbis.model.AbstractOpenBISNode;
import ch.eth.scu.importer.at.gui.viewers.openbis.model.OpenBISProjectNode;
import ch.eth.scu.importer.processors.lsrfortessa.BDFACSDIVAFCSProcessor.Experiment;
import ch.eth.scu.importer.processors.lsrfortessa.model.SampleDescriptor;
import ch.eth.scu.importer.processors.model.AbstractDescriptor;
import ch.eth.scu.importer.processors.model.DatasetDescriptor;
import ch.eth.scu.importer.ui_elements.lsrfortessa.gui.editors.data.model.BDLSRFortessaFCSMetadata;
import ch.eth.scu.importer.ui_elements.lsrfortessa.gui.viewers.data.model.ExperimentNode;
import ch.eth.scu.importer.ui_elements.lsrfortessa.gui.viewers.data.model.FolderNode;

/**
 * Metadata editor panel.
 * @author Aaron Ponti
 */
public class BDLSRFortessaFCSEditor extends AbstractEditor {

	protected TreeModel dataModel;
	protected TreeModel openBISModel;
	
	protected List<OpenBISProjectNode> openBISProjects = 
			new ArrayList<OpenBISProjectNode>();

	// List of experiments from the Data Model
	protected List<FolderNode> dataFolders = 
			new ArrayList<FolderNode>();
	
	// List of metadata mappers
	protected List<BDLSRFortessaFCSMetadata> metadataMappersList =
			new ArrayList<BDLSRFortessaFCSMetadata>();

	// Indicate which of the List<BDLSRFortessaFCSMetadata> is the 
	// active one
	protected int currentExperimentIndex = -1;

	protected JLabel labelFolderName;
	protected JLabel labelExpName;
	protected JComboBox<String> comboGeometryList;
	protected JComboBox<OpenBISProjectNodeWrapper> comboProjectList;
	protected JTextArea expDescription;
	
	/**
	 * Constructor
	 */
	public BDLSRFortessaFCSEditor(AbstractViewer dataViewer, 
			OpenBISViewer openBISViewer) {

		// Store the reference to the data and openBIS viewers
		super(dataViewer, openBISViewer);

		// Create a GridBagLayout
		GridBagLayout gridBagLayout = new GridBagLayout();
		panel.setLayout(gridBagLayout);

	}

	/**
	 * ActionPerformed method from the ActionListener interface
	 * @param e The ActionEvent object
	 */
	public void actionPerformed(ActionEvent e) {
	}

	/**
	 * Map the data and openBIS models
	 * @throws Exception 
	 */
	public void init(ObserverActionParameters params) throws Exception {
		
		// Make sure both viewers have completed their models
		if (!openBISViewer.isReady() || !dataViewer.isReady()) {
			return;
		}
		
		// Init the metadata
		if (initMetadata()) {
			
			// Create the widgets
			createUIElements(params);

		}
		
	}

	/**
	 * Once the metadata has been completely filled, this method makes
	 * sure to update the data model (generated by the Processor) to be
	 * ready to be saved to the XML properties file. 
	 */
	@Override
	public boolean updateDataModel() {
		
		// Check whether we have some experiments to update
		if (metadataMappersList.size() == 0) {
			return false;
		}

		// Go over all experiments
		for (BDLSRFortessaFCSMetadata metadata : metadataMappersList) {
			
			// Get the experiment node
			ExperimentNode expNode = 
					(ExperimentNode) metadata.folderNode.getChildAt(0);
			assert(expNode.getType().equals("Experiment"));
			
			// We first start by updating the Experiment descriptor itself
			Experiment expDescr = (Experiment) expNode.getUserObject();
	
			// Set the openBIS experiment identifier
			Map<String, String> expOpenBISAttributes = 
					new Hashtable<String, String>();
			expOpenBISAttributes.put("openBISIdentifier", 
					metadata.getOpenBISExerimentIdentifier());
			expOpenBISAttributes.put("openBISSpaceIdentifier", 
					metadata.getOpenBISSpaceIdentifier());
			expDescr.setOpenBISAttributes(expOpenBISAttributes);

			// Set the description
			Map<String, String> expUserAttributes = 
					new Hashtable<String, String>();
			expUserAttributes.put("description", metadata.description); 
			expDescr.setUserAttributes(expUserAttributes);

			// Now get the Trays and Specimens children of the Experiment
			for (int i = 0; i < expNode.getChildCount(); i++) {
	
				// Get the i-th child node
				AbstractNode firstLevelSampleNode =
						(AbstractNode) expNode.getChildAt(i);
	
				// Get the Sample Descriptor
				SampleDescriptor firstLevelSample =
						(SampleDescriptor) firstLevelSampleNode.getUserObject();
	
				// Make sure we have a Tray or a Specimen
				assert((firstLevelSample.getType().equals("Tray") ||
	                    firstLevelSample.getType().equals("Specimen")));

				// Set the openBIS space and experiment identifiers
				Map<String, String> firstLevelOpenBISAttributes = 
						new Hashtable<String, String>();
				firstLevelOpenBISAttributes.put(
						"openBISSpaceIdentifier", 
						metadata.getOpenBISSpaceIdentifier());
				firstLevelOpenBISAttributes.put(
						"openBISExperimentIdentifier", 
						metadata.getOpenBISExerimentIdentifier());
				firstLevelSample.setOpenBISAttributes(
						firstLevelOpenBISAttributes);

				// In case we have a Tray, we set the geometry
				Map<String, String> firstLevelUserAttributes = 
						new Hashtable<String, String>();
				firstLevelUserAttributes.put(
						"trayGeometry", 
						metadata.trayGeometry);
				firstLevelSample.setUserAttributes(
						firstLevelUserAttributes);

				// Now go over the children
				for (int j = 0; j < firstLevelSampleNode.getChildCount(); j++ ) {
	
					// Get the j-th child node
					AbstractNode secondLevelSampleNode =
							(AbstractNode) firstLevelSampleNode.getChildAt(j);
	
					// Get the Sample Descriptor
					SampleDescriptor secondLevelSample =
							(SampleDescriptor) secondLevelSampleNode.getUserObject();
	
					// Make sure we have a Specimen or a Tube
					assert((secondLevelSample.getType().equals("Specimen") ||
	                        secondLevelSample.getType().equals("Tube")));
	
					// Set the openBIS space and experiment identifiers
					Map<String, String> secondLevelOpenBISAttributes = 
							new Hashtable<String, String>();
					secondLevelOpenBISAttributes.put(
							"openBISSpaceIdentifier", 
							metadata.getOpenBISSpaceIdentifier());
					secondLevelOpenBISAttributes.put(
							"openBISExperimentIdentifier", 
							metadata.getOpenBISExerimentIdentifier());
					secondLevelSample.setOpenBISAttributes(
							secondLevelOpenBISAttributes);					
	
					// Now go over the children
					for (int k = 0; k < secondLevelSampleNode.getChildCount(); k++ ) {
	
						// Get the j-th child node
						AbstractNode thirdLevelSampleNode =
								(AbstractNode) secondLevelSampleNode.getChildAt(k);
	
						// A third-level node can contain a Tube or an FCS file
						AbstractDescriptor abstractSample = (AbstractDescriptor)
								thirdLevelSampleNode.getUserObject();
	
						// Make sure we have a Well or a FCSFile
						assert((abstractSample.getType().equals("Well") ||
	                            abstractSample.getType().equals("FCSFile")));
	
						if (abstractSample.getType().equals("Well")	) {
	
							// Cast
							SampleDescriptor thirdLevelSample = (SampleDescriptor)
									thirdLevelSampleNode.getUserObject();
	
							// Set the openBIS space and experiment identifiers
							Map<String, String> thirdLevelOpenBISAttributes = 
									new Hashtable<String, String>();
							thirdLevelOpenBISAttributes.put(
									"openBISSpaceIdentifier", 
									metadata.getOpenBISSpaceIdentifier());
							thirdLevelOpenBISAttributes.put(
									"openBISExperimentIdentifier", 
									metadata.getOpenBISExerimentIdentifier());
							thirdLevelSample.setOpenBISAttributes(
									thirdLevelOpenBISAttributes);					
							
							// And now we set up the associated FCS file
	
							// Get the child (one!): the FCS file
							assert(thirdLevelSampleNode.getChildCount() == 1);
	
							AbstractNode fourthLevelSampleNode = (AbstractNode)
									thirdLevelSampleNode.getChildAt(0);
							DatasetDescriptor fcsFile = (DatasetDescriptor)
									fourthLevelSampleNode.getUserObject();
	
							// Set the openBIS space and experiment identifiers
							Map<String, String> fourthLevelOpenBISAttributes = 
									new Hashtable<String, String>();
							fourthLevelOpenBISAttributes.put(
									"openBISExperimentIdentifier", 
									metadata.getOpenBISExerimentIdentifier());
							fcsFile.setOpenBISAttributes(
									fourthLevelOpenBISAttributes);	
	
						} else {
	
							// Here we have an FCS file
	
							// Cast
							DatasetDescriptor fcsFile = (DatasetDescriptor)
									thirdLevelSampleNode.getUserObject();

							// Set the openBIS space and experiment identifiers
							Map<String, String> fourthLevelOpenBISAttributes = 
									new Hashtable<String, String>();
							fourthLevelOpenBISAttributes.put(
									"openBISExperimentIdentifier", 
									metadata.getOpenBISExerimentIdentifier());
							fcsFile.setOpenBISAttributes(
									fourthLevelOpenBISAttributes);	

						}
					}
				}
			}
		}

		return true;
	}	

	/**
	 * Update metadata and UI
	 */
	public void updateAll(ObserverActionParameters params) {
	
		// Update the currentExperimentIndex property
		currentExperimentIndex = dataFolders.indexOf(params.node);
		if (currentExperimentIndex == -1) {
			return;
		}
		
		// Update the UI
		updateUIElements();
	}

	/**
	 * Map the data and openBIS models
	 * @throws Exception 
	 */
	protected boolean initMetadata() {
		
		// Make sure both viewers have completed their models
		if (!openBISViewer.isReady() || !dataViewer.isReady()) {
			return false;
		}
		
		// Store the and openBIS nodes
		storeOpenBISProjects();
		storeDataFolders();
		
		// Check that there is at least one entry in each of the 
		// arrays
		if (dataFolders.size() == 0 || openBISProjects.size() == 0) {
			// TODO: Inform the user
			return false;
		}
		
		// Create all BDLSRFortessaFCSMetadata objects and initially 
		// assign each folder to the first project
		for (FolderNode node : dataFolders) {
			metadataMappersList.add(
					new BDLSRFortessaFCSMetadata(
							node, openBISProjects.get(0)));
		}
		
		// Initially we set the first openBIS project as a target
		// for all experiments
		currentExperimentIndex = 0;
		
		// Return success
		return true;
	}
	
	/**
	 * Renders all widgets on the panel
	 * @throws Exception if some openBIS identifiers cannot be computed
	 */
	protected void createUIElements(ObserverActionParameters params) throws Exception {

		// Make sure both viewers have completed their models
		if (metadataMappersList.size() == 0) {
			return;
		}

		// If we are repainting this panel, let's make sure we delete the
		// child components already displayed.
		if (panel.getComponentCount() > 0) {
			panel.removeAll();
			panel.revalidate(); 
		}

		// Get selected metadata element
		BDLSRFortessaFCSMetadata metadata = metadataMappersList.get(
				currentExperimentIndex);
		
		/*
		 *  Folder name
		 */
		
		// Constraints
		GridBagConstraints constraints = new GridBagConstraints();
		constraints.anchor = GridBagConstraints.NORTHWEST;
		constraints.fill = GridBagConstraints.HORIZONTAL;

		// Create a label for the folder
		constraints.insets = new Insets(10, 10, 10, 10);
		constraints.weightx = 1;
		constraints.weighty = 0;
		constraints.gridx = 0;
		constraints.gridy = 0;
		labelFolderName = new JLabel(metadata.folderNode.toString());
		labelFolderName.setIcon(new ImageIcon(
				this.getClass().getResource("icons/folder.png")));
		panel.add(labelFolderName, constraints);

		/*
		 *  Experiment name
		 */
		
		String expName = metadata.folderNode.getChildAt(0).toString();
		
		// Create a label for the experiment
		constraints.insets = new Insets(0, 20, 0, 20);
		constraints.weightx = 1;
		constraints.weighty = 0;
		constraints.gridx = 0;
		constraints.gridy = 1;
		labelExpName = new JLabel(expName);
		labelExpName.setIcon(new ImageIcon(
				this.getClass().getResource("icons/experiment.png")));		
		panel.add(labelExpName, constraints);

		/*
		 * Description label
		 */
		
		// Create a label for the experiment description
		constraints.insets = new Insets(0, 20, 0, 20);
		constraints.weightx = 1;
		constraints.weighty = 0;
		constraints.gridx = 0;
		constraints.gridy = 2;
		JLabel labelExpDescription = new JLabel("Description");
		labelExpDescription.setHorizontalAlignment(JLabel.CENTER);
		panel.add(labelExpDescription, constraints);

		/*
		 * Description text area
		 */
		constraints.weightx = 1;
		constraints.weighty = 0;
		constraints.gridx = 0;
		constraints.gridy = 3;
		expDescription = new JTextArea(metadata.description);
		expDescription.setLineWrap(true);
		expDescription.getDocument().addDocumentListener(new DocumentListener() {

			@Override
			public void insertUpdate(DocumentEvent e) {
				updateExpDescription();
			}

			@Override
			public void removeUpdate(DocumentEvent e) {
				updateExpDescription();
			}

			@Override
			public void changedUpdate(DocumentEvent e) {
				updateExpDescription();
			}
        });
		JScrollPane areaScrollPane = new JScrollPane(expDescription);
		areaScrollPane.setVerticalScrollBarPolicy(
		                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
		areaScrollPane.setMinimumSize(new Dimension(400, 50));
		areaScrollPane.setPreferredSize(new Dimension(400, 50));
		panel.add(areaScrollPane, constraints);
		
		/*
		 *  Tray geometry label
		 */

		// Create a label for the geometry combo box
		constraints.insets = new Insets(10, 10, 10, 10);
		constraints.weightx = 1;
		constraints.weighty = 0;
		constraints.gridx = 0;
		constraints.gridy = 4;
		JLabel labelGeometry = new JLabel("Plate geometry");
		labelGeometry.setHorizontalAlignment(JLabel.CENTER);
		panel.add(labelGeometry, constraints);
		
		/*
		 *  Tray geometry combo
		 */
		
		// Display a combo box with the geometries
		ArrayList<String> supportedGeometries =
				metadata.supportedTrayGeometries;
		comboGeometryList = new JComboBox<String>();
		for (String geometry : supportedGeometries) {

			// Add the geometry
			comboGeometryList.addItem(geometry);

		}		

		// Select the correct one
		comboGeometryList.setSelectedIndex(supportedGeometries.indexOf(
				metadata.trayGeometry));

		// When a geometry is selected, update the corresponding 
		// experiment in the data model 
		comboGeometryList.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (e.getActionCommand().equals("comboBoxChanged")) {

					String geometry =
							(String)
							((JComboBox<String>)
									e.getSource()).getSelectedItem();
					
					// Update the metadata object with the new projects
					metadataMappersList.get(
							currentExperimentIndex).trayGeometry =
							geometry;

				}
			}
		});

		// Add the geometry combo box
		constraints.insets = new Insets(0, 20, 0, 20);
		constraints.weightx = 1;
		constraints.weighty = 0;
		constraints.gridx = 0;
		constraints.gridy = 5;
		panel.add(comboGeometryList, constraints);

		/*
		 *  Label openBIS projects
		 */

		// Create a label for the openBIS projects
		constraints.insets = new Insets(10, 10, 10, 10);
		constraints.weightx = 1;
		constraints.weighty = 0;
		constraints.gridx = 0;
		constraints.gridy = 6;
		JLabel labelProjects = new JLabel("Target openBIS project");
		labelProjects.setHorizontalAlignment(JLabel.CENTER);
		panel.add(labelProjects, constraints);
		
		/*
		 *  Tray openBIS projects
		 */
		
		// Store the project in a JCombo box
		comboProjectList = new JComboBox<OpenBISProjectNodeWrapper>();
		
		for (OpenBISProjectNode s : openBISProjects) {

			// Add the BDLSRFortessaFCSMetadata object
			comboProjectList.addItem(new OpenBISProjectNodeWrapper(s));

		}
		
		// Select the correct one
		comboProjectList.setSelectedIndex(openBISProjects.indexOf(
				metadata.openBISProjectNode));

		// When a project is selected, update the corresponding 
		// experiment in the data model 
		comboProjectList.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (e.getActionCommand().equals("comboBoxChanged")) {

					// Get the BDLSRFortessaFCSMetadata object
					OpenBISProjectNodeWrapper projectNodeWrapper =
							(OpenBISProjectNodeWrapper)
							((JComboBox<OpenBISProjectNodeWrapper>)
									e.getSource()).getSelectedItem();
					OpenBISProjectNode projectNode = projectNodeWrapper.node;

					// Update the metadata object with the new projects
					metadataMappersList.get(
							currentExperimentIndex).openBISProjectNode =
							projectNode;

				}
			}
		});
	
		// Add the project combo box
		constraints.insets = new Insets(0, 20, 0, 20);
		constraints.weightx = 1;
		constraints.weighty = 0;
		constraints.gridx = 0;
		constraints.gridy = 7;
		panel.add(comboProjectList, constraints);

		/*
		 *  Spacer
		 */
		
		// Add a spacer
		constraints.gridx = 0;
		constraints.gridy = 8;
		constraints.weightx = 1.0;
		constraints.weighty = 1.0;
		panel.add(new JLabel(""), constraints);
		
		// In case this was called when then window was already visible (i.e.
		// if the login failed the first time and this panel was drawn without
		// children)
		panel.revalidate();

	}

	/**
	 * Update all widgets on the panel
	 */
	private void updateUIElements() {
		
		// Get the active metadata object
		BDLSRFortessaFCSMetadata metadata = metadataMappersList.get(
				currentExperimentIndex);

		// Update the folder name
		labelFolderName.setText(metadata.getFolderName());
		
		// Update the experiment name
		labelExpName.setText(metadata.getExperimentName());

		// Update the description
		expDescription.setText(metadata.description);

		// Update the geometry
		comboGeometryList.setSelectedIndex(
				metadata.supportedTrayGeometries.indexOf(
				metadata.trayGeometry));

		// Update the project
		comboProjectList.setSelectedIndex(openBISProjects.indexOf(
				metadata.openBISProjectNode));
	}
	
	/**
	 * Collects and stores openBIS projects for mapping
	 * @return list of openBIS nodes
	 */
	private void storeOpenBISProjects() {
		
		// Store the openBIS model
		openBISModel = openBISViewer.getDataModel();
		
        // We extract all projects from the openBIS model and create a list
		// with which we will then create JComboBox associated to each project
		// from the data model
		openBISProjects = new ArrayList<OpenBISProjectNode>();
		
		AbstractOpenBISNode openBISRoot = 
				(AbstractOpenBISNode) openBISModel.getRoot();

		// Iterate over the space nodes (there should be at least one)
		for (int i = 0; i < openBISRoot.getChildCount(); i++) {

			// Get the Space
			AbstractOpenBISNode openBISSpaceNode = 
					(AbstractOpenBISNode) openBISRoot.getChildAt(i);

			// Go over the child Projects
			int n = openBISSpaceNode.getChildCount();

			for (int j = 0; j < n; j++) {

				// Get the OpenBISProjectNode
				OpenBISProjectNode openBISProjectNode = 
						(OpenBISProjectNode) openBISSpaceNode.getChildAt(j);

				// Add it to the list: we wrap it into a wrapper 
				// class to override the toString() method; we do 
				// this because in constrast to what happens in the
				// openBIS viewer, here we need the (openBIS) identifier
				//  instead of the code.
				openBISProjects.add(openBISProjectNode);

			}
		}
	}

	/**
	 * Collects and stores data folders for mapping
	 * @return list of openBIS nodes
	 */
	private void storeDataFolders() {

		// Reset the dataFolders list
		dataFolders = new ArrayList<FolderNode>();

		// Store the data model
		dataModel = dataViewer.getDataModel();
		
		// We extract all experiments from the data model
		RootNode dataRoot = (RootNode) dataModel.getRoot();
		
		// First level are the folder nodes 
		int dataNChildren = dataRoot.getChildCount();

		for (int i = 0; i < dataNChildren; i++) {

			// Get the FolderNode
			FolderNode folderNode = (FolderNode) dataRoot.getChildAt(i);

				// Store the reference to the ExperimentNode
				dataFolders.add(folderNode);
		}        
	}

	/**
	 * We update the experiment description on the fly while the user 
	 * is typing in the Text Area.
	 */
	protected void updateExpDescription() {

		// Get the active metadata object
		BDLSRFortessaFCSMetadata metadata = metadataMappersList.get(
				currentExperimentIndex);
		
		// Store the experiment description
		metadata.description = expDescription.getText();
    }
	
	/**
	 * Wrapper class that "overrides" OpenBISProjectNode's toString()
	 * method to use in the Editor. 
	 * @author Aaron Ponti
	 *
	 */
	public class OpenBISProjectNodeWrapper  {
		public OpenBISProjectNode node;
		
		/**
		 * Constructor.
		 * @param node An OpenBISProjectNode node.
		 */
		public OpenBISProjectNodeWrapper(OpenBISProjectNode node) {
			this.node = node;
		}
		
		// "Override" the toString method of OpenBISProjectNode
		public String toString() {
			return node.getIdentifier();
		}
	}
}
